cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'awscli'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'libgit2'
brew 'mitmproxy'
brew 'mysql'
brew 'openssl'
brew 'wget'

#brew 'slackcat'

cask 'aerial'
cask 'atom'
cask 'appcleaner'
cask 'battle-net'
cask 'evernote'
cask 'firefox'
cask 'flux'
cask 'gitup'
cask 'google-chrome'
cask 'java'
cask 'mysqlworkbench'
cask 'pixlr'
cask 'skype'
cask 'spotify'
cask 'telegram'
cask 'the-unarchiver'
cask 'torbrowser'
cask 'transmission'
cask 'vlc'

#cask 'slack'
