#!/bin/bash

# next repos compose this
# https://github.com/cowboy/dotfiles
set -euf -o pipefail

sudo -v

# Initialize.
if [[ ! -d ~/.dotfiles ]]; then
  new_dotfiles_install=1
  # ~/.dotfiles doesn't exist? Clone it!
  echo "Downloading dotfiles"
  git clone --recursive git://github.com/floresrobles/dotfiles.git ~/.dotfiles
  cd ~/.dotfiles
else
  # Make sure we have the latest files.
  echo "Updating dotfiles"
  cd ~/.dotfiles
  git pull
  git submodule update --init --recursive --quiet
fi

bash script/bootstrap

# XCode permission
# TODO: install XCode, lol, and accept license
echo "If next fails, install xcode and open it"
echo sudo -S  xcodebuild -license accept
