#!/bin/bash

# next repos compose this
# https://github.com/cowboy/dotfiles
set -euf -o pipefail

sudo -v

# Initialize.
if [[ ! -d ~/.dotfiles ]]; then
  new_dotfiles_install=1
  # ~/.dotfiles doesn't exist? Clone it!
  echo "Downloading dotfiles"
  git clone --recursive https://github.com/floresrobles/dotfiles.git ~/.dotfiles
  cd ~/.dotfiles
else
  # Make sure we have the latest files.
  echo "Updating dotfiles"
  cd ~/.dotfiles
  git pull
  git submodule update --init --recursive --quiet
fi

# holman's bootstrap
bash script/bootstrap

# change shell
chsh -s /bin/zsh

# oh my zsh
sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# XCode permission
# TODO: install XCode, lol, and accept license
echo "If next fails, install xcode and open it"
sudo xcodebuild -license accept
