#!/bin/bash

set -euf -o pipefail

# Initialize.
echo "› ~/.dotfiles"
if [[ ! -d ~/.dotfiles ]]; then
  new_dotfiles_install=1
  # ~/.dotfiles doesn't exist? Clone it!
  echo "Downloading dotfiles"
  git clone --recursive https://github.com/floresrobles/dotfiles.git ~/.dotfiles
fi

cd ~/.dotfiles
sh ./bin/dot-install
